# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a190e582500d0469fc98c6c0c93dea25453f196f5434a11b0379e2a7e756d8e53e57168041462f146b107887f0c3decc7b28b5fe4f11ddf05874081f770ff5ef

test:
  secret_key_base: ed296219a92d92261dc17d71f1f2f62e60c8e0d5b7d4f5de608a302964be78a47217003f5513b58ec98464894a46947e4ef4568fcf0e875a7bbeb4d8e57f23a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
